CREATE CONSTRAINT memory_node_id IF NOT EXISTS FOR (n:MemoryNode) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT workflow_id IF NOT EXISTS FOR (n:Workflow) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT screen_id IF NOT EXISTS FOR (n:Screen) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT business_rule_id IF NOT EXISTS FOR (n:BusinessRule) REQUIRE n.id IS UNIQUE;
CREATE INDEX memory_node_type IF NOT EXISTS FOR (n:MemoryNode) ON (n.type);
CREATE INDEX memory_node_confidence IF NOT EXISTS FOR (n:MemoryNode) ON (n.confidence);
// Relationship vocabulary: MENTIONS, CHUNKED_INTO, VALIDATED_BY, SHOWN_ON, USES_SCREEN, GOVERNED_BY, REQUIRES_VALIDATION, CREATES_INSIGHT, NEXT_STEP.
